### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by tashisrael** [tashisrael/Recipe-app#9]
### Hello Code Reviewer;
- In this milestone, we are 2 coding partners i.e. @tashisrael and @MohamedCK
- [This is the link to our project](https://github.com/users/tashisrael/projects/1)

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi @tashisrael and @MohamedCK,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] The project link you provided is broken, Please add a valid project link.

![image](https://user-images.githubusercontent.com/68796232/218500037-b5de3599-6c6b-4613-9511-f7c284ca88f7.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 
- Tasks distributed equally ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
